[package]
name = "ergo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
scrap = "0.5"
repng = "0.2"
opencv = "0.64"

[dev-dependencies]
show-image = "0.12.3"